//the array containing all anime quotes
anime_quotes = [
    "It's not the face that makes someone a monster; it's the choices they make with their lives. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "The only thing we're allowed to do is to believe that we won't regret the choice we made. - Levi Ackerman, Attack on Titan",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "It's not the face that makes someone a monster; it's the choices they make with their lives. - Naruto",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "It's not the face that makes someone a monster; it's the choices they make with their lives. - Naruto",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn",
    "The world isn't perfect. But it's there for us, doing the best it can... that's what makes it so damn beautiful. - Roy Mustang, Fullmetal Alchemist",
    "If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. - Naruto",
    "I'm not stupid. I'm just too lazy to show how smart I am. - Oreki Houtarou, Hyouka",
    "If you don't win, you can't get revenge. - Killua Zoldyck, Hunter x Hunter",
    "No matter how deep the night, it always turns to day, eventually. - Brook, One Piece",
    "If you win, you live. If you lose, you die. If you don't fight, you can't win! - Eren Yeager, Attack on Titan",
    "I am Justice! I protect the innocent and those who fear evil. I'm the one who will become the god of a new world that everyone desires! - Light Yagami, Death Note",
    "It's okay not to be okay as long as you are not giving up. - Karen Salmansohn"
];

// export default anime_quotes;